export const navlinks = [
   {
      name: "Ana səhifə",
      path: "/",
   },
   {
      name: "Haqqımızda",
      path: "/about",
   },
   {
      name: "Əlaqə",
      path: "/contact",
   },
   {
      name: "Cart",
      path: "/cart",
   },
];

export const products = [
   {
      id: 1,
      name: "Göz Nuru",
      author: "Aliyeva Natavan",
      authorSlug: "aliyeva-natavan",
      size: "100x100",
      price: 100,
      authorImg: "/author.jpeg",
      imageSrc: "/Frame2.png",
      imageAlt: "Tall slender porcelain bottle with natural clay textured body and cork stopper.",
   },
   {
      id: 2,
      name: "Göz Nuru",
      author: "Vəliyeva sara",
      authorSlug: "veliyeva-sara",
      size: "100x100",
      price: 150,
      authorImg:
         "https://s3-alpha-sig.figma.com/img/9f3b/48c5/3792ff2bd34385b4856a7279f9f15589?Expires=1725840000&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=CQgLHNAtlg~nFOj3YWyQoYUj3HO2t1vlANnRpkG-YSi0NrVa6ud1sgKMYZW2QIs7S7MUA6XLMx7Ks9D7KE0xg-ilKXbWx5mLNQCuMqx~uOEYPD4tH-ETWljfoU75pJtn-7BOWfHbFFRCMAisZ60cHrYHYxLjHEUZAYfkwFq52erdmqPbJLhSfnCxtUqDdTCr4v~P0iT2otfT3L-gSnWrmcfQ62U7f0PhSFP-kKQzjezlo5YFxnSKKdbdzHXASF1y9do~47w0t4GdyhuYaKwClMzuQUy50kX~576bPDsL00dJG6JPrgcb6phagzBgBqNF-TsdOlBKoQHmzBDJABn3nw__",
      imageSrc: "/painting.jpeg",
      imageAlt: "A wooden desk organizer with various compartments for office supplies.",
   },
   {
      id: 3,
      name: "Göz Nuru",
      author: "Əlixan Məhərrəmov",
      authorSlug: "elixan-meherremov",
      size: "100x100",
      price: 300,
      authorImg: "https://images.pexels.com/photos/837358/pexels-photo-837358.jpeg?auto=compress&cs=tinysrgb&w=600",
      imageSrc: "/painting2.jpeg",
      imageAlt: "A classic white ceramic mug with a simple design.",
   },
   {
      id: 4,
      name: "Göz Nuru",
      author: "Aliyeva Natavan",
      authorSlug: "aliyeva-natavan",
      size: "100x100",
      price: 155,
      authorImg:
         "https://s3-alpha-sig.figma.com/img/9f3b/48c5/3792ff2bd34385b4856a7279f9f15589?Expires=1725840000&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=CQgLHNAtlg~nFOj3YWyQoYUj3HO2t1vlANnRpkG-YSi0NrVa6ud1sgKMYZW2QIs7S7MUA6XLMx7Ks9D7KE0xg-ilKXbWx5mLNQCuMqx~uOEYPD4tH-ETWljfoU75pJtn-7BOWfHbFFRCMAisZ60cHrYHYxLjHEUZAYfkwFq52erdmqPbJLhSfnCxtUqDdTCr4v~P0iT2otfT3L-gSnWrmcfQ62U7f0PhSFP-kKQzjezlo5YFxnSKKdbdzHXASF1y9do~47w0t4GdyhuYaKwClMzuQUy50kX~576bPDsL00dJG6JPrgcb6phagzBgBqNF-TsdOlBKoQHmzBDJABn3nw__",

      imageSrc: "/painting.jpeg",
      imageAlt: "A brown leather wallet with multiple compartments for cards and cash.",
   },
   {
      id: 5,
      name: "Göz Nuru",
      author: "Ahmədov Nurlan",
      authorSlug: "ehmedov-nurlan",
      size: "100x100",
      price: 200,
      authorImg: "https://images.pexels.com/photos/837358/pexels-photo-837358.jpeg?auto=compress&cs=tinysrgb&w=600",
      imageSrc: "/painting2.jpeg",
      imageAlt: "A clear glass vase with a minimalist design.",
   },
   {
      id: 6,
      name: "Göz Nuru",
      author: "Ahmədov Azər",
      authorSlug: "ehmedov-azer",
      size: "100x100",
      price: 15,
      authorImg: "https://images.pexels.com/photos/837358/pexels-photo-837358.jpeg?auto=compress&cs=tinysrgb&w=600",
      imageSrc: "/painting.jpeg",
      imageAlt: "A sleek metal pen holder with a modern design.",
   },
   {
      id: 7,
      name: "Göz Nuru",
      author: "Bayramova Fidan",
      authorSlug: "bayramova-fidan",
      size: "100x100",
      price: 40,
      authorImg:
         "https://s3-alpha-sig.figma.com/img/9f3b/48c5/3792ff2bd34385b4856a7279f9f15589?Expires=1725840000&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=CQgLHNAtlg~nFOj3YWyQoYUj3HO2t1vlANnRpkG-YSi0NrVa6ud1sgKMYZW2QIs7S7MUA6XLMx7Ks9D7KE0xg-ilKXbWx5mLNQCuMqx~uOEYPD4tH-ETWljfoU75pJtn-7BOWfHbFFRCMAisZ60cHrYHYxLjHEUZAYfkwFq52erdmqPbJLhSfnCxtUqDdTCr4v~P0iT2otfT3L-gSnWrmcfQ62U7f0PhSFP-kKQzjezlo5YFxnSKKdbdzHXASF1y9do~47w0t4GdyhuYaKwClMzuQUy50kX~576bPDsL00dJG6JPrgcb6phagzBgBqNF-TsdOlBKoQHmzBDJABn3nw__",
      imageSrc: "/painting.jpeg",
      imageAlt: "A soft cotton throw blanket in a neutral color.",
   },
   {
      id: 8,
      name: "Göz Nuru",
      author: "Əliyev Ayxan",
      authorSlug: "eliyev-ayxan",
      size: "100x100",
      price: 25,
      authorImg: "https://images.pexels.com/photos/837358/pexels-photo-837358.jpeg?auto=compress&cs=tinysrgb&w=600",
      imageSrc: "/painting.jpeg",
      imageAlt: "A wooden picture frame with a classic design.",
   },
   {
      id: 9,
      name: "Göz Nuru",
      author: "Mustafayev Mustafa",
      authorSlug: "mustafayev-mustafa",
      size: "100x100",
      price: 30,
      authorImg: "https://images.pexels.com/photos/837358/pexels-photo-837358.jpeg?auto=compress&cs=tinysrgb&w=600",
      imageSrc: "/painting2.jpeg",
      imageAlt: "A stainless steel bottle with a sleek design.",
   },
   {
      id: 10,
      name: "Göz Nuru",
      author: "Mustafayev Mustafa",
      authorSlug: "mustafayev-mustafa",
      size: "100x100",
      price: 20,
      authorImg: "https://images.pexels.com/photos/837358/pexels-photo-837358.jpeg?auto=compress&cs=tinysrgb&w=600",
      imageSrc: "/painting.jpeg",
      imageAlt: "A handwoven basket perfect for storage and decoration.",
   },
];
